FROM eclipse-temurin:17.0.4.1_1-jdk-centos7 AS openedge 

RUN yum install sysvinit-tools -y && \
    yum clean all

ADD ../binaries/PROGRESS_OE_12.6_LNX_64.tar.gz /install/openedge

COPY response126-pro2.ini /install/openedge/response.ini
ENV TERM xterm
RUN /install/openedge/proinst -b /install/openedge/response.ini -l /install/install_oe.log -n && \
    rm /usr/dlc/progress.cfg

FROM eclipse-temurin:17.0.4.1_1-jdk-centos7 AS oracle

RUN yum install sysvinit-tools -y && \
    yum clean all

USER root

RUN mkdir /install/ && \
    mkdir -p /opt/oracle && \
    mkdir -p /opt/oraInventory && \
    yum install libaio libnsl -y && \
    yum install unzip -y && \
    groupadd -g 54321 oinstall && \
    groupadd -g 54322 dba && \
    groupadd -g 54323 oper && \
    useradd -g oinstall oracle 

COPY ./binaries/LINUX.X64_193000_client_home.zip /install/ 

WORKDIR /install

RUN unzip LINUX.X64_193000_client_home.zip -d /opt/oracle/client && \
    chown -R oracle:oinstall /opt/oracle && \
    chown -R oracle:oinstall /opt/oraInventory && \
    chmod -R 775 /opt 
    

WORKDIR /opt/oracle/client/lib
RUN rm -rf libexpat.so.1 && \
    ln -s libexpat.so.1.6.8 libexpat.so.1 && \
    ldconfig /opt/oracle/client/lib

USER oracle
COPY ./pro2/tnsnames.ora /opt/oracle/client/network/admin/tnsnames.ora

FROM eclipse-temurin:17.0.4.1_1-jdk-centos7
 
RUN yum install sysvinit-tools net-tools -y && \
    yum install libaio libnsl -y && \
    mkdir /usr/dlc && \
    mkdir /usr/wrk && \ 
    mkdir /opt/oracle && \
    mkdir /opt/oraInventory

COPY --from=openedge /usr/dlc /usr/dlc
COPY --from=openedge /usr/wrk /usr/wrk
COPY --from=openedge /etc/openedge.d /etc/openedge.d
COPY --from=oracle /opt/oracle /opt/oracle
COPY --from=oracle /opt/oraInventory /opt/oraInventory



WORKDIR /etc/openedge.d

RUN ls -all

USER root

WORKDIR /usr/dlc/bin

RUN chown root _* && \
    chmod 4755 _* && \
    groupadd -g 1000 openedge && \
    useradd -r -u 1000 -g openedge openedge && \
    groupadd -g 54321 oinstall && \
    groupadd -g 54322 dba && \
    groupadd -g 54323 oper && \
    useradd -g oinstall oracle 

ENV TERM xterm   
ENV DLC=/usr/dlc
ENV WRKDIR=/usr/wrk
ENV PATH=$PATH:$DLC:$DLC/bin

# create directories and files as root
RUN mkdir /app/ && \
    mkdir /app/pas && \
    mkdir /app/license/ && \
    # hand them over to user 'openedge'
    chown -R openedge:openedge /app/ && \
    chown -R openedge:openedge /usr/dlc/servers/pasoe && \
    rm -rf /usr/dlc/src && \
    rm -rf /usr/dlc/empty && \
    rm -rf /usr/dlc/sports* && \
    rm -rf /usr/dlc/isports* && \
    rm -rf /usr/dlc/demo 

USER openedge

ENV PROCFG=/app/license/progress.cfg
VOLUME /app/license


