FROM eclipse-temurin:17.0.11_9-jdk-jammy AS install 

ADD ../binaries/PROGRESS_OE_12.8.3_LNX_64.tar.gz /install/openedge

COPY response128_pas_prod.ini /install/openedge/response.ini
COPY clean_oe_files.sh /install/openedge/
ENV TERM=xterm
RUN /install/openedge/proinst -b /install/openedge/response.ini -l /install/install_oe.log -n 

RUN ./install/openedge/clean_oe_files.sh pasoe

FROM eclipse-temurin:17.0.11_9-jdk-jammy

RUN apt update && \
    apt install netbase && \
    mkdir /usr/dlc && \
    mkdir /usr/wrk

COPY --from=install /usr/dlc /usr/dlc
COPY --from=install /usr/wrk /usr/wrk
COPY --from=install /etc/openedge.d /etc/openedge.d
COPY --from=install /etc/openedge /etc/openedge
COPY --from=install /etc/progress /etc/progress

WORKDIR /usr/dlc/bin

RUN chown root _* && \
    chmod 4755 _*
    #already removed the sql stuff for PASOE images, no need to chmod
    #chmod 755 _sql* 

ENV TERM=xterm   
ENV DLC=/usr/dlc
ENV WRKDIR=/usr/wrk
ENV PATH=$PATH:$DLC:$DLC/bin

RUN groupadd -g 1000 openedge && \
    useradd -r -u 1000 -g openedge openedge

# create directories and files as root
RUN mkdir /app/ && \
    mkdir /app/pas && \
    chown -R openedge:openedge /app/ 

    # hand them over to user 'openedge'
WORKDIR /app/pas
ADD start.sh /app/pas
# create a basic pas instance for production & enable health check
# next to that remove some unnecessary files for this PASOE container
RUN pasman create -p 8220 -P 8221 -s 8222 -Z prod -v prodpas && \
    /app/pas/prodpas/bin/tcman.sh feature HealthCheck=on && \
    chown -R openedge:openedge /usr/dlc/servers/pasoe /app/pas/prodpas 

# we need to enable TCP 
RUN echo 'tcp    6 TCP' >> /etc/protocols 
    # we should remove progress.cfg once we're done building for distribution
    # rm /usr/dlc/progress.cfg

USER openedge

EXPOSE 8220 8221 8899

LABEL maintainer="rdroge@progress.com"

CMD [ "/app/pas/start.sh" ]





