FROM adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.14.1_1-slim AS openedge
ADD ./binaries/PROGRESS_OE_12.5.2_LNX_64.tar.gz /install/openedge

COPY response125.ini /install/openedge/response.ini

ENV TERM xterm
RUN /install/openedge/proinst -b /install/openedge/response.ini -l /install/install_oe.log -n && \
    rm /usr/dlc/progress.cfg

FROM adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.14.1_1-slim AS oracle 

USER root

RUN mkdir /install/ && \
    mkdir -p /opt/oracle && \
    mkdir -p /opt/oraInventory && \
    apk add libaio libnsl && \
    apk add unzip && \
    addgroup -g 54321 oinstall && \
    addgroup -g 54322 dba && \
    addgroup -g 54323 oper && \
    adduser -u 54321 -G oinstall oracle -D

COPY ./binaries/LINUX.X64_193000_client_home.zip /install/ 

WORKDIR /install

RUN unzip LINUX.X64_193000_client_home.zip -d /opt/oracle/client && \
    chown -R oracle:oinstall /opt/oracle && \
    chown -R oracle:oinstall /opt/oraInventory && \
    chmod -R 775 /opt 
    

WORKDIR /opt/oracle/client/lib
RUN rm -rf libexpat.so.1 && \
    ln -s libexpat.so.1.6.8 libexpat.so.1 && \
    ldconfig /opt/oracle/client/lib

USER oracle
COPY ./pro2/tnsnames.ora /opt/oracle/client/network/admin/tnsnames.ora

FROM adoptopenjdk/openjdk11:x86_64-alpine-jdk-11.0.14.1_1-slim

RUN mkdir /usr/dlc && \
    mkdir /usr/wrk && \ 
    mkdir /opt/oracle && \
    mkdir /opt/oraInventory

COPY --from=openedge /usr/dlc /usr/dlc
COPY --from=openedge /usr/wrk /usr/wrk
COPY --from=oracle /opt/oracle /opt/oracle
COPY --from=oracle /opt/oraInventory /opt/oraInventory


WORKDIR /usr/dlc/bin

RUN chown root _* && \
    chmod 4755 _* && \
    addgroup -g 1000 openedge && \
    adduser -S -u 1000 -G openedge openedge && \
    addgroup -g 54321 oinstall && \
    addgroup -g 54322 dba && \
    addgroup -g 54323 oper && \
    adduser -u 54321 -G oinstall oracle -D

ENV TERM xterm   
ENV DLC=/usr/dlc
ENV WRKDIR=/usr/wrk
ENV PATH=$PATH:$DLC:$DLC/bin

# create directories and files as root
RUN mkdir /app/ && \
    mkdir /app/pas && \
    mkdir /app/license/ && \
    # hand them over to user 'openedge'
    chown -R openedge:openedge /app/ && \
    chown -R openedge:openedge /usr/dlc/servers/pasoe && \
    rm -rf /usr/dlc/src && \
    rm -rf /usr/dlc/empty && \
    rm -rf /usr/dlc/sports* && \
    rm -rf /usr/dlc/isports* && \
    rm -rf /usr/dlc/demo

USER openedge

ENV PROCFG=/app/license/progress.cfg
VOLUME /app/license


