ALTER PROFILE "DEFAULT" LIMIT 
  password_life_time unlimited;
ALTER SESSION SET CONTAINER=ORCLPDB1;
CREATE USER pro2 IDENTIFIED BY pro2password;
GRANT ALL PRIVILEGES TO pro2;
ALTER USER pro2 QUOTA UNLIMITED ON USERS;
commit;
exit;