FROM rwdroge/openedge_pas_base:12.5.2

USER root

RUN mkdir /install/ && \
    mkdir /install/pro2/ && \
    mkdir -p /opt/oracle && \
    mkdir -p /opt/oraInventory && \
    chown -R openedge:openedge /install && \
    apk add libaio && \
    apk add unzip && \
    addgroup -g 54321 oinstall && \
    addgroup -g 54322 dba && \
    addgroup -g 54323 oper && \
    adduser -u 54321 -G oinstall oracle -D

COPY ./LINUX.X64_193000_client_home.zip ./clientsetup.rsp /install/ 

WORKDIR /install

RUN unzip LINUX.X64_193000_client_home.zip -d /opt/oracle/client && \
    chown -R oracle:oinstall /opt/oracle && \
    chown -R oracle:oinstall /opt/oraInventory && \
    chmod -R 775 /opt && \ 
    rm -rf LINUX.X64_193000_client_home.zip

WORKDIR /opt/oracle/client/lib
RUN rm -rf libexpat.so.1 && \
    ln -s libexpat.so.1.6.8 libexpat.so.1 && \
    ldconfig /opt/oracle/client/lib

USER oracle

ENV LD_LIBRARY_PATH /opt/oracle/client/lib:$LD_LIBRARY_PATH
ENV ORACLE_HOME /opt/oracle/client

USER root

COPY Pro2-6.3.0.bin response.properties /install/pro2/

WORKDIR /install/pro2

RUN ./Pro2-6.3.0.bin -i Silent -f response.properties && \  
    chown -R openedge:openedge /install/pro2 -R && \
    rm -rf Pro2-6.3.0.bin

USER openedge

WORKDIR /install/pro2/bprepl/Scripts

COPY start.sh /install/pro2/start.sh 
COPY tnsnames.ora /opt/oracle/client/network/admin/tnsnames.ora
COPY replProc.pf sports2020.pf ./ 
COPY schemaholder/* /install/pro2/db

RUN /install/pro2/Pro2Web/bin/oeprop.sh +AppServer.SessMgr.Pro2Web.agentStartupParam="-T ../temp -pf /install/pro2/bprepl/Scripts/replProc.pf" 

CMD ["/install/pro2/start.sh"]

EXPOSE 9991 9992